#!/usr/bin/env python3
"""wayland_bindgen.py — generate Mojo bindings for libwayland-client.

Reads wayland protocol XML (core wayland.xml, or extension protocols like
xdg-shell.xml) and emits:

  - wayland/protocol/{protocol_name}_types.mojo   (enums/enums-as-consts + arg structs)
  - wayland/protocol/{protocol_name}.mojo         (interface handles + request stubs)
  - wayland/c/wayland_shim.h / wayland_shim.c     (thin C shim for event listeners)

Design notes (Mojo 1.0.0b2, verified against the compiler directly):
  * libwayland-client only exports a small symbol set — per-interface request
    functions (wl_surface_commit etc.) are header-inline. Requests therefore
    lower to wl_proxy_marshal_array / wl_proxy_marshal_array_constructor_versioned
    via Mojo `external_call` (proven working on this compiler).
  * Opaque handles = UnsafePointer[NoneType, MutAnyOrigin]; null check via Int(ptr)==0.
  * Events: a C shim defines real wl_*_listener structs whose callbacks call
    Mojo trampolines emitted into wayland/gen/listeners.mojo. This keeps the
    unstable ABI out of Mojo entirely.
  * Requests with new_id return a new handle; destructors (request name="destroy"
    / wl_proxy_destroy) emit as `destroy()`.

Usage:
  python3 scripts/wayland_bindgen.py /usr/share/wayland/wayland.xml \
      [--protocols /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml ...]
  Output: wayland/ (package) + build with `pixi run mojo package wayland -o wayland.mojopkg`.
"""

from __future__ import annotations

import argparse
import os
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

# ----------------------------- type mapping -------------------------------
# wayland.xml <arg type="..."> -> Mojo type expression. Verified against
# libwayland-client ABI (wl_argument union in wayland-client-core.h).

MOJO_PTR = "UnsafePointer[NoneType, MutAnyOrigin]"

# (xml type, interface attr present?) -> (mojo type, wl_argument tag)
# wl_argument tags: i(int) u(uint) f(fixed) s(string) o(object) n(new_id) a(array) h(fd)
TYPE_MAP: Dict[Tuple[str, bool], Tuple[str, str]] = {
    ("int", False): ("Int32", "i"),
    ("uint", False): ("UInt32", "u"),
    ("fixed", False): ("Float64", "f"),
    ("string", False): ("WLString", "s"),
    ("object", True): (MOJO_PTR, "o"),
    ("object", False): (MOJO_PTR, "o"),
    ("new_id", True): (MOJO_PTR, "n"),
    ("new_id", False): (MOJO_PTR, "n"),
    ("array", False): (MOJO_PTR, "a"),
    ("fd", False): ("Int32", "h"),
    ("uint", True): ("UInt32", "u"),
}

# Fixed-point conversion: wl_fixed is int24.8
FIXED_SCALE = 256.0

HEADER = '''# AUTO-GENERATED by scripts/wayland_bindgen.py — DO NOT EDIT.
# Source: {source}
# Regenerate: pixi run wayland-gen
from wayland.core import WLPtr, WLArgument, WLString, MAX_EVENT_ARGS, _cstr, _shim_listen, _shim_event_pop, _shim_string_free, wl_proxy_marshal_array, wl_proxy_marshal_array_constructor_versioned, wl_proxy_destroy
from std.memory import stack_allocation
'''

CORE_HEADER = '''# core.mojo — hand-written runtime support for generated wayland bindings.
# This file is NOT regenerated.
from std.ffi import external_call
from std.memory import stack_allocation

comptime MUT_PTR = UnsafePointer[NoneType, MutAnyOrigin]

# Opaque object handle. All wl_* objects (display, surface, seat, ...) are
# pointers to wl_proxy internally.
comptime WLPtr = MUT_PTR

# A protocol string argument. The C shim copies to a NUL-terminated buffer
# that lives for the duration of the request; Mojo side just carries bytes.
comptime WLString = UnsafePointer[Byte, MutAnyOrigin]

# Max protocol args of any single event across known protocols.
comptime MAX_EVENT_ARGS = 16


def _cstr(s: String) -> UnsafePointer[Int8, MutUntrackedOrigin]:
    """Null-terminated C char* view into a Mojo String (borrowed).
    Copies internally so immutable callers are fine."""
    var copy = String(s)
    var cs = copy.as_c_string_slice()
    return rebind[UnsafePointer[Int8, MutUntrackedOrigin]](cs)


def _shim_interface(name: String) -> WLPtr:
    """Resolve a wl_*_interface data symbol by name via the C shim."""
    return external_call["wayland_shim_interface", WLPtr](_cstr(name))


def _proxy_constructor_versioned(proxy: WLPtr, opcode: UInt32, args: UnsafePointer[WLArgument, MutAnyOrigin], iface_name: String, version: UInt32) raises -> WLPtr:
    """Constructor helper: resolves the interface record by name through the
    C shim (wl_*_interface are data symbols, invisible to external_call).

    The `version` argument is IGNORED in favour of the parent proxy's
    negotiated version - this mirrors what wayland-scanner emits
    (`wl_proxy_get_version(parent)`), because a child object must never
    claim a newer version than its factory object was bound with."""
    var iface = _shim_interface(iface_name)
    if Int(iface) == 0:
        raise Error("wayland: unknown interface " + iface_name)
    var parent_version = wl_proxy_get_version(proxy)
    return wl_proxy_marshal_array_constructor_versioned(proxy, opcode, args, iface, parent_version)


# --- event capture shim ---
# The C shim installs a wl_dispatcher per proxy that captures every event's
# opcode + marshalled arguments into a queue. listen() returns the queue
# handle; pop() takes the queue so the C side needs no proxy lookups.


def _shim_listen(proxy: WLPtr, iface_name: String, out_queue: UnsafePointer[WLPtr, MutAnyOrigin]) -> Int32:
    """Install the capture dispatcher on a proxy. Returns 0 on success and
    writes the queue handle to out_queue (out param: the C side writes one
    pointer, so this takes a single-slot buffer, not the slot's value)."""
    return external_call["wayland_shim_listen", Int32](proxy, _cstr(iface_name), out_queue)


def _shim_event_pop(queue: WLPtr, opcode: UInt32, out_args: UnsafePointer[WLArgument, MutAnyOrigin]) -> Int32:
    """Pop one captured event into out_args. Returns its opcode or -1.
    Any returned string args are malloc'd copies owned by the caller
    (free via wayland_shim_string_free)."""
    return external_call["wayland_shim_event_pop", Int32](queue, opcode, out_args)


def _shim_string_free(s: WLString):
    """Free a string copy returned by a popped 's' argument."""
    external_call["wayland_shim_string_free", NoneType](s)


def shim_interface(name: String) raises -> WLPtr:
    """Resolve a protocol interface record (wl_registry_interface etc.) by
    name through the C shim. Data symbols are invisible to external_call;
    the shim matches them by name. Needed for generic binds where the
    caller picks the interface (e.g. binding xdg_wm_base or wl_seat from
    the registry)."""
    var iface = _shim_interface(name)
    if Int(iface) == 0:
        raise Error("wayland: unknown interface " + name)
    return iface
'''


WRAPPER_DEFS = '''

def wl_display_connect(name: UInt64) -> WLPtr:
    # NOTE: an explicit explicit-name argument is REQUIRED. A zero-arg
    # external_call on Mojo 1.0.0b2 emits a call with an UNDEFINED first
    # register (garbage or stack pointer), which libwayland treats as a
    # literal socket name — connect then fails depending on surrounding
    # codegen. Passing UInt64(0) = NULL name is the only safe form.
    return external_call["wl_display_connect", WLPtr](name)


def wl_display_disconnect(display: WLPtr):
    external_call["wl_display_disconnect", NoneType](display)


def wl_display_roundtrip(display: WLPtr) -> Int32:
    return external_call["wl_display_roundtrip", Int32](display)


def wl_display_dispatch(display: WLPtr) -> Int32:
    return external_call["wl_display_dispatch", Int32](display)


def wl_display_dispatch_pending(display: WLPtr) -> Int32:
    return external_call["wl_display_dispatch_pending", Int32](display)


def wl_display_flush(display: WLPtr) -> Int32:
    return external_call["wl_display_flush", Int32](display)


def wl_display_get_fd(display: WLPtr) -> Int32:
    return external_call["wl_display_get_fd", Int32](display)


def wl_display_get_error(display: WLPtr) -> Int32:
    return external_call["wl_display_get_error", Int32](display)


def wl_display_get_protocol_error(display: WLPtr, out_interface: WLPtr, out_id: UnsafePointer[UInt32, MutAnyOrigin]) -> UInt32:
    return external_call["wl_display_get_protocol_error", UInt32](display, out_interface, out_id)


def wl_proxy_get_id(proxy: WLPtr) -> UInt32:
    return external_call["wl_proxy_get_id", UInt32](proxy)


def wl_proxy_get_version(proxy: WLPtr) -> UInt32:
    return external_call["wl_proxy_get_version", UInt32](proxy)


def wl_proxy_destroy(proxy: WLPtr):
    external_call["wl_proxy_destroy", NoneType](proxy)


def wl_proxy_marshal_array(proxy: WLPtr, opcode: UInt32, args: UnsafePointer[WLArgument, MutAnyOrigin]):
    external_call["wl_proxy_marshal_array", NoneType](proxy, opcode, args)


def wl_proxy_marshal_array_constructor_versioned(proxy: WLPtr, opcode: UInt32, args: UnsafePointer[WLArgument, MutAnyOrigin], iface: WLPtr, version: UInt32) -> WLPtr:
    return external_call["wl_proxy_marshal_array_constructor_versioned", WLPtr](proxy, opcode, args, iface, version)


def wl_proxy_marshal_array_flags(proxy: WLPtr, opcode: UInt32, args: UnsafePointer[WLArgument, MutAnyOrigin], iface: WLPtr, version: UInt32, flags: UInt32) -> WLPtr:
    return external_call["wl_proxy_marshal_array_flags", WLPtr](proxy, opcode, args, iface, version, flags)


def wl_proxy_add_listener(proxy: WLPtr, listener: WLPtr, data: WLPtr) -> Int32:
    return external_call["wl_proxy_add_listener", Int32](proxy, listener, data)


def wl_proxy_set_user_data(proxy: WLPtr, data: WLPtr):
    external_call["wl_proxy_set_user_data", NoneType](proxy, data)


def wl_proxy_get_user_data(proxy: WLPtr) -> WLPtr:
    return external_call["wl_proxy_get_user_data", WLPtr](proxy)


def wl_proxy_set_queue(proxy: WLPtr, queue: WLPtr):
    external_call["wl_proxy_set_queue", NoneType](proxy, queue)


def wl_list_init(lst: WLPtr):
    external_call["wl_list_init", NoneType](lst)


def wl_array_init(arr: WLPtr):
    external_call["wl_array_init", NoneType](arr)


def wl_array_release(arr: WLPtr):
    external_call["wl_array_release", NoneType](arr)


def wl_array_add(arr: WLPtr, size: Int) -> WLPtr:
    return external_call["wl_array_add", WLPtr](arr, size)
'''

# wl_argument is an 8-byte union on x86_64 (largest member is one pointer;
# int members occupy only 4 of the 8-byte slot). Mojo side we express it as
# an 8-byte cell so Mojo arrays can be passed straight into the C shim.
ARGUMENT_UNION = '''

# wl_argument mirror (8 bytes on x86_64). Byte buffer with typed constructors;
# layout matches wayland-client's union EXACTLY.
struct WLArgument(Copyable, Movable, ImplicitlyCopyable):
    var raw: InlineArray[Byte, 8]

    def __init__(out self):
        self.raw = InlineArray[Byte, 8](uninitialized=True)
        for i in range(8):
            self.raw[i] = Byte(0)

    def __init__(out self, *, copy: Self):
        self.raw = copy.raw

    @staticmethod
    def store32(b: UnsafePointer[Byte, MutAnyOrigin], off: Int, value: Int32):
        b[off] = Byte(value & 0xFF)
        b[off + 1] = Byte((value >> 8) & 0xFF)
        b[off + 2] = Byte((value >> 16) & 0xFF)
        b[off + 3] = Byte((value >> 24) & 0xFF)

    @staticmethod
    def store64(b: UnsafePointer[Byte, MutAnyOrigin], off: Int, value: UInt):
        b[off] = Byte(value & 0xFF)
        b[off + 1] = Byte((value >> 8) & 0xFF)
        b[off + 2] = Byte((value >> 16) & 0xFF)
        b[off + 3] = Byte((value >> 24) & 0xFF)
        b[off + 4] = Byte((value >> 32) & 0xFF)
        b[off + 5] = Byte((value >> 40) & 0xFF)
        b[off + 6] = Byte((value >> 48) & 0xFF)
        b[off + 7] = Byte((value >> 56) & 0xFF)

    @staticmethod
    def make_i(value: Int32) -> Self:
        var a = Self()
        Self.store32(a.raw.unsafe_ptr(), 0, value)
        return a

    @staticmethod
    def make_u(value: UInt32) -> Self:
        var a = Self()
        var bits: UInt = UInt(value)
        Self.store32(a.raw.unsafe_ptr(), 0, Int32(bits))
        return a

    @staticmethod
    def make_f(value: Float64) -> Self:
        # wl_fixed: int24.8 signed fixed-point
        var fixed: Int32 = Int32(value * 256.0)
        return Self.make_i(fixed)

    @staticmethod
    def make_s(value: WLString) -> Self:
        return Self._from_ptr(UInt(Int(value)))

    @staticmethod
    def make_o(value: WLPtr) -> Self:
        return Self._from_ptr(UInt(Int(value)))

    @staticmethod
    def make_n(value: WLPtr) -> Self:
        return Self._from_ptr(UInt(Int(value)))

    @staticmethod
    def make_a(value: WLPtr) -> Self:
        return Self._from_ptr(UInt(Int(value)))

    @staticmethod
    def make_h(value: Int32) -> Self:
        return Self.make_i(value)

    @staticmethod
    def _from_ptr(val: UInt) -> Self:
        var a = Self()
        Self.store64(a.raw.unsafe_ptr(), 0, val)
        return a
'''


def snake_to_camel(s: str) -> str:
    parts = s.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def snake(s: str) -> str:
    return s.replace("-", "_")


def mojo_ident(s: str) -> str:
    """Sanitize an xml name into a Mojo identifier."""
    out = snake(s)
    if out[0].isdigit():
        out = "_" + out
    return out


@dataclass
class Arg:
    name: str
    type: str            # xml type
    interface: Optional[str]  # for object/new_id
    enum: Optional[str]  # enum attr, if any
    summary: str = ""


@dataclass
class Request:
    name: str
    args: List[Arg]
    opcode: int
    # xml: type="destructor" on the request element
    is_destructor: bool = False


@dataclass
class Event:
    name: str
    args: List[Arg]
    opcode: int


@dataclass
class Enum:
    name: str
    kind: str  # "enum" | "bitmask"
    values: List[Tuple[str, int]]  # (NAME, value)


@dataclass
class Interface:
    name: str
    version: int
    requests: List[Request]
    events: List[Event]
    enums: List[Enum]


@dataclass
class Protocol:
    name: str
    copyright: str
    interfaces: List[Interface]


# ------------------------------ parsing ----------------------------------

def parse_arg(el: ET.Element) -> Arg:
    return Arg(
        name=mojo_ident(el.get("name", "")),
        type=el.get("type", ""),
        interface=el.get("interface"),
        enum=el.get("enum"),
        summary=el.get("summary", ""),
    )


def parse_protocol(path: str) -> Protocol:
    root = ET.parse(path).getroot()
    assert root.tag == "protocol", f"{path}: root is {root.tag}, expected protocol"
    proto_name = root.get("name")
    assert proto_name is not None, f"{path}: protocol missing name"
    proto = Protocol(
        name=proto_name,
        copyright=(root.findtext("copyright") or "").strip(),
        interfaces=[],
    )
    for iface_el in root.findall("interface"):
        iface_name = iface_el.get("name")
        assert iface_name is not None, f"{path}: interface missing name"
        iface = Interface(
            name=iface_name,
            version=int(iface_el.get("version", "1")),
            requests=[],
            events=[],
            enums=[],
        )
        for i, req_el in enumerate(iface_el.findall("request")):
            req_name = req_el.get("name")
            assert req_name is not None, "request missing name"
            iface.requests.append(Request(
                name=req_name,
                args=[parse_arg(a) for a in req_el.findall("arg")],
                opcode=i,
                is_destructor=req_el.get("type") == "destructor",
            ))
        for i, ev_el in enumerate(iface_el.findall("event")):
            ev_name = ev_el.get("name")
            assert ev_name is not None, "event missing name"
            iface.events.append(Event(
                name=ev_name,
                args=[parse_arg(a) for a in ev_el.findall("arg")],
                opcode=i,
            ))
        for enum_el in iface_el.findall("enum"):
            enum_name = enum_el.get("name")
            assert enum_name is not None, "enum missing name"
            vals: List[Tuple[str, int]] = []
            for v in enum_el.findall("entry"):
                entry_name = v.get("name")
                assert entry_name is not None, "entry missing name"
                vals.append((entry_name, int(v.get("value", "0"), 0)))
            iface.enums.append(Enum(
                name=enum_name,
                kind="bitmask" if enum_el.get("bitfields") == "true" else "enum",
                values=vals,
            ))
        proto.interfaces.append(iface)
    return proto


# ------------------------------ emission ---------------------------------

def emit_arg_struct(name: str, args: List[Arg], doc: str) -> str:
    """Emit a Mojo struct carrying event args (used by the listener shim path)."""
    lines = [f"struct {name}:", f'    """{doc}"""', ""]
    if not args:
        lines.append("    comptime _empty = True")
    for a in args:
        mojo_ty, _tag = TYPE_MAP.get((a.type, a.interface is not None), (MOJO_PTR, "o"))
        lines.append(f"    var {a.name}: {mojo_ty}")
    lines.append("")
    ctor_args = ", ".join(f"{a.name}: {TYPE_MAP.get((a.type, a.interface is not None), (MOJO_PTR,'o'))[0]}" for a in args) or ""
    lines.append(f"    def __init__(out self{', ' + ctor_args if ctor_args else ''}):")
    if args:
        for a in args:
            lines.append(f"        self.{a.name} = {a.name}")
    else:
        lines.append("        pass")
    return "\n".join(lines) + "\n"


def emit_request_stub(iface: Interface, req: Request, proto_name: str) -> str:
    """Emit a Mojo def for one request.

    Lowering rules:
      - last arg of type new_id with no interface (generic) -> returns generic handle
        (rare: only wl_marshal-style). Standard new_id -> constructor path.
      - request with new_id -> wl_proxy_marshal_array_constructor_versioned
      - destructor requests -> marshal + wl_proxy_destroy
      - plain requests -> wl_proxy_marshal_array
    """
    op = req.opcode
    fn = f"{snake(iface.name)}_{snake(req.name)}"
    args_sig = []
    for a in req.args:
        if a.type == "new_id":
            continue  # created by libwayland; not caller-supplied
        mojo_ty, _ = TYPE_MAP.get((a.type, a.interface is not None), (MOJO_PTR, "o"))
        args_sig.append(f"{a.name}: {mojo_ty}")
    args_sig_str = "self: WLPtr" if not args_sig else "self: WLPtr, " + ", ".join(args_sig)

    new_id_args = [a for a in req.args if a.type == "new_id"]
    is_constructor = bool(new_id_args) and not req.is_destructor

    body_indent = " " * 4
    if is_constructor:
        ret = "WLPtr"
        if new_id_args[-1].interface:
            lines = [f"def {fn}({args_sig_str}) raises -> {ret}:"]
        else:
            lines = [f"def {fn}({args_sig_str}) -> {ret}:"]
        lines.append(f'{body_indent}# opcode {op}: {req.name}')
        # new_id interface: either concrete (emit static interface name resolution)
        # or generic — for generic we require caller to pass interface via helper.
        # For concrete iface, we look up the interface struct in the C shim by name.
        last = new_id_args[-1]
        if last.interface:
            # CRITICAL: wl_closure_marshal indexes the argument array by
            # SIGNATURE POSITION, not dense-packed. new_id keeps its slot
            # (libwayland writes the new object there; it must arrive zeroed).
            # Example: get_xdg_surface signature "no" → surface goes in slot
            # 1, slot 0 stays zero. Dense-packing caused the compositor to
            # read an uninitialized slot as the new_id and reject the call.
            non_new_id = [a for a in req.args if a.type != "new_id"]
            lines.append(f"{body_indent}# opcode {op}: {req.name}, creates {last.interface}")
            lines.append(f"{body_indent}# slots follow wire-signature positions (new_id slot zeroed)")
            lines.append(f"{body_indent}var args_array = stack_allocation[{max(1, len(req.args))}, WLArgument]()")
            for i, a in enumerate(req.args):
                if a.type == "new_id":
                    continue  # slot stays zeroed; libwayland writes the new proxy id
                tag = TYPE_MAP[(a.type, a.interface is not None)][1]
                lines.append(f"{body_indent}args_array[{i}] = WLArgument.make_{tag}({a.name})")
            version = int(iface.version or 1)
            lines.append(
                f"{body_indent}return _proxy_constructor_versioned("
                f'self, {op}, args_array, "{last.interface}", {version})'
            )
        else:
            # Generic new_id (e.g. wl_registry.bind, wire signature "usun"):
            # the caller supplies the target interface. wayland-scanner
            # synthesizes two extra wire args after the XML-listed args:
            #   make_s(interface->name) + make_u(version)
            # and passes the interface POINTER only to the constructor (for
            # the created proxy). The wrapper therefore takes: iface ptr,
            # iface name string, XML-listed non-new_id args, and version
            # (used both as wire arg and constructor version).
            non_new = [a for a in req.args if a.type != "new_id"]
            lines = [
                f"def {fn}(self: WLPtr, iface: WLPtr, iface_name: WLString, "
                + ", ".join(f"{a.name}: {TYPE_MAP[(a.type, a.interface is not None)][0]}"
                            for a in non_new)
                + ", version: UInt32) -> WLPtr:"
            ]
            lines.append(f"{body_indent}# opcode {op}: generic constructor (caller picks interface;")
            lines.append(f"{body_indent}# scanner synthesizes 's' interface-name + 'u' version wire args)")
            # Slots follow wire-signature positions: XML args in order, then
            # the scanner-synthesized string + version wire args. The new_id
            # slot is EXCLUDED from the wire signature itself (libwayland
            # writes the new proxy id into a slot it appends internally for
            # the generic-bind case: signature "usun", n is last).
            lines.append(f"{body_indent}var args_array = stack_allocation[{len(non_new) + 2}, WLArgument]()")
            m = 0
            for a in non_new:
                tag = TYPE_MAP[(a.type, a.interface is not None)][1]
                lines.append(f"{body_indent}args_array[{m}] = WLArgument.make_{tag}({a.name})")
                m += 1
            lines.append(f"{body_indent}args_array[{len(non_new)}] = WLArgument.make_s(iface_name)")
            lines.append(f"{body_indent}args_array[{len(non_new) + 1}] = WLArgument.make_u(version)")
            lines.append(f"{body_indent}return wl_proxy_marshal_array_constructor_versioned(self, {op}, args_array, iface, version)")
        return "\n".join(lines) + "\n"

    if req.is_destructor:
        lines = [f"def {fn}({args_sig_str}):"]
        lines.append(f"{body_indent}# opcode {op}: destructor")
        lines.append(f"{body_indent}var args_array = stack_allocation[{max(1, len(req.args))}, WLArgument]()")
        for i, a in enumerate(req.args):
            if a.type == "new_id":
                continue  # slot zeroed; args marshal by wire position
            tag = TYPE_MAP[(a.type, a.interface is not None)][1]
            lines.append(f"{body_indent}args_array[{i}] = WLArgument.make_{tag}({a.name})")
        lines.append(f"{body_indent}wl_proxy_marshal_array(self, {op}, args_array)")
        lines.append(f"{body_indent}wl_proxy_destroy(self)")
        return "\n".join(lines) + "\n"

    # plain request — same wire-position rule (new_id slots stay zeroed)
    lines = [f"def {fn}({args_sig_str}):"]
    lines.append(f"{body_indent}# opcode {op}")
    lines.append(f"{body_indent}var args_array = stack_allocation[{max(1, len(req.args))}, WLArgument]()")
    for i, a in enumerate(req.args):
        if a.type == "new_id":
            continue
        tag = TYPE_MAP[(a.type, a.interface is not None)][1]
        lines.append(f"{body_indent}args_array[{i}] = WLArgument.make_{tag}({a.name})")
    lines.append(f"{body_indent}wl_proxy_marshal_array(self, {op}, args_array)")
    return "\n".join(lines) + "\n"


def emit_interface_module(proto: Protocol) -> str:
    """Emit one generated .mojo with all interface handle structs."""
    parts: List[str] = []
    parts.append("# AUTO-GENERATED — DO NOT EDIT.")
    parts.append(f"# from protocol '{proto.name}'")
    parts.append(
        "from wayland.core import WLPtr, WLArgument, WLString, MAX_EVENT_ARGS, "
        "_cstr, _shim_listen, _shim_event_pop, _shim_string_free, _proxy_constructor_versioned, "
        "wl_proxy_marshal_array, "
        "wl_proxy_marshal_array_constructor_versioned, wl_proxy_destroy"
    )
    parts.append("from std.memory import stack_allocation")
    parts.append("")
    for iface in proto.interfaces:
        parts.append(f"# ---- {iface.name} v{iface.version} ----")
        # event opcodes (used with the dispatcher shim)
        for ev in iface.events:
            parts.append(f"comptime {snake(iface.name).upper().removeprefix('WL_')}_{ev.name.upper()}_OP: UInt32 = {ev.opcode}")
        if iface.events:
            parts.append("")
        for enum in iface.enums:
            for (vname, vval) in enum.values:
                const_name = f"{iface.name.upper().removeprefix('WL_')}_{enum.name.upper()}_{vname.upper()}"
                parts.append(f"comptime {const_name}: UInt32 = {vval}")
            parts.append("")
        for req in iface.requests:
            parts.append(emit_request_stub(iface, req, proto.name))
            parts.append("")
        # event capture: listen + typed per-event poll/pop accessors
        if iface.events:
            short = snake(iface.name)
            parts.append(
                f"def {short}_listen(self: WLPtr, out_queue: UnsafePointer[WLPtr, MutAnyOrigin]) -> Int32:"
                f'\n    """Register the capture dispatcher on {iface.name} and write'
                f'\n    the queue handle to out_queue[0]. Pop events from that queue."""'
                f"\n    return _shim_listen(self, \"{iface.name}\", out_queue)"
                f"\n"
            )
            ev_blocks: List[str] = []
            for ev in iface.events:
                dec = f"{short}_next_{snake(ev.name)}"
                non_new = [a for a in ev.args if a.type != "new_id"]
                if non_new:
                    ev_blocks.append(
                        f"def {dec}(queue: WLPtr, out_args: UnsafePointer[WLArgument, MutAnyOrigin]) -> Bool:"
                        f'\n    """Pop the next pending {ev.name} event into out_args (len {len(non_new)}). False = none."""'
                        f"\n    var rc = _shim_event_pop(queue, {ev.opcode}, out_args)"
                        f"\n    return rc == {ev.opcode}"
                        f"\n"
                    )
                else:
                    ev_blocks.append(
                        f"def {dec}(queue: WLPtr) -> Bool:"
                        f'\n    """Pop the next pending {ev.name} event. False = none."""'
                        f"\n    var scratch = stack_allocation[1, WLArgument]()"
                        f"\n    var rc = _shim_event_pop(queue, {ev.opcode}, scratch)"
                        f"\n    return rc == {ev.opcode}"
                        f"\n"
                    )
            parts.extend(ev_blocks)
    return "\n".join(parts)


def emit_c_shim(proto: Protocol) -> str:
    """Emit the C listener shim. For each interface with events, emit:
         - struct wl_{name}_listener_mojo with C fn pointers
         - bridge callbacks that call Mojo trampolines (declared `extern Mojo`)
    """
    # The C side is protocol-specific; generated into wayland/c/shim.c
    raise NotImplementedError


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("xml", nargs="+", help="protocol XML file(s); first must be core wayland.xml")
    ap.add_argument("--out", default="wayland", help="output package dir")
    args = ap.parse_args()

    core = parse_protocol(args.xml[0])
    extras = [parse_protocol(p) for p in args.xml[1:]]

    out = args.out
    os.makedirs(out, exist_ok=True)
    os.makedirs(os.path.join(out, "gen"), exist_ok=True)
    with open(os.path.join(out, "core.mojo"), "w") as f:
        f.write(CORE_HEADER + WRAPPER_DEFS + ARGUMENT_UNION)
    with open(os.path.join(out, "gen", f"{core.name}.mojo"), "w") as f:
        f.write(emit_interface_module(core))
    for extra in extras:
        with open(os.path.join(out, "gen", f"{extra.name}.mojo"), "w") as f:
            f.write(emit_interface_module(extra))
    print(f"wrote {out}/core.mojo + {len(extras)+1} protocol module(s)")
    # __init__.mojo files: package + gen subpackage
    with open(os.path.join(out, "gen", "__init__.mojo"), "w") as f:
        f.write("# AUTO-GENERATED — DO NOT EDIT.\n")
    init_lines = ["from wayland.core import *"]
    for extra in [core] + extras:
        init_lines.append(f"from wayland.gen.{extra.name} import *")
    with open(os.path.join(out, "__init__.mojo"), "w") as f:
        f.write("\n".join(init_lines) + "\n")


if __name__ == "__main__":
    main()